//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknorixHiring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobProfile
    {
        public int Id { get; set; }
        public Nullable<int> JobProfileId { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> Posted_date { get; set; }
        public Nullable<System.DateTime> Closing_date { get; set; }
    }
}
